### ISSUE TITLE
MacBenesh BMN for Worksheets

### ISSUE THREAD

**Issue by rsryman** [rryman/BB1-Worksheets#1]
Uploaded to Dropbox folder For Robyn > BB1_Worksheets:
1. a newly created .pdf file converted from a .ps file printed from MacBenesh, containing all BMN I couldn't find in RAD Foundations .ps files
2. a .docx file with a suggested format for the Worksheet, based on the D241 worksheets edited by you for NBS; the BMN in this file is based on RAD Foundations .ps files, mirrored to create the other side where possible, and "greyed" using the Format Picture > Picture > Recolor > Accent Color 4 Light)

I tried to match the BMN in our iBook1 as best I could, but some of the sign dimensions are slightly different. The notation currently in the .docx file might need to be updated to match the newly created notation -- to be discussed.

TO BE DECIDED: p. 27 of the .docx file contains empty stave and frames created in MacBenesh, in case we decide to replace those currently in the file. 

TO BE CONFIRMED: The first greyed image on p. 4 (bras bas) is Accent Color 3 Light which prints too light on my printer; thereafter I have used Accent Color 4 Light, OK?

At your convenience, please check the BMN in the .pdf. I will await you feedback and update this notation before I paste clips into the .docx file.

**Comment by rryman** [comment]
Robyn needs to create a new repository for BB4 Worksheets. Then the comment below needs to be moved to BB4 Worksheets: 

RE WORKSHEETS: Rhonda to make note to update all MacBenesh where hands hang beside thighs (level sign at vertical & horizontal centre of 2nd space) re pp. 16, 83, 85, 105, 113 Q3&4

**Comment by rryman** [comment]
I have updated Page 4 of BB1 Worksheets (see attached).
Please **print out** Page 4 and let me know if the opacity of the grey signs is to your liking.
They are presently at 25% capacity. It is easy to change this percentage, we just have to decide how light they can be without disappearing.
I will not proceed with other pages until we agree on the opacity.
[2018_05_18_BeneshWorksheetsBook1.pdf](https://github.com/rryman/BB1-Worksheets/files/2016964/2018_05_18_BeneshWorksheetsBook1.pdf)

**Comment by rsryman** [comment]
I just received a new laser toner cartridge which I will install tomorrow so I can print out and check p. 4.

**Comment by rsryman** [comment]
I can't seem to get the old laser toner cartridge out of my printer to
install the new cartridge.

Should have asked Arthur to help me do this on Saturday. Can this wait
until Friday?

**Comment by rryman** [comment]
Yes it can wait, I am in no hurry.

---

**Comment by rsryman** [comment]
We agree that RObyn will edit in Adobe Illustrator to make all MacBenesh signs consistent with the BMN in BB1. This mens that all future edits must be done from the pdf.
