### ISSUE TITLE
Accessing Files from one computer to the other

### ISSUE THREAD

**Issue by rryman** [rryman/BB1-Worksheets#2]
If you are having difficulty with DropBox on your old computer and you want to share files, there is still a way to do it. I suggest doing a Google Hangout with Arthur and he will be able to walk you through how to network the two computers. He says Apple has simplified the process.

It is supposedly also possible to access DropBox via the internet. I am not sure if you still require the most up-to-date DropBox app on your computer, but it might be worth a try by going to:
https://www.dropbox.com/home and seeing if it works.

**Comment by rsryman** [comment]
We will set up a time to talk me through accessing Dropbox via Chrome.
