### ISSUE TITLE
BB1 Worksheet File - 2018_05_18

### ISSUE THREAD

**Issue by rryman** [rryman/BB1-Worksheets#3]
[2018_05_18_BeneshWorksheetsBook1.pdf](https://github.com/rryman/BB1-Worksheets/files/2069612/2018_05_18_BeneshWorksheetsBook1.pdf)

**Comment by rryman** [comment]
**DONE**

**Robyn to email (see suggested response below in two different comments Jun 4) Canan once BB1 Worksheets are completed and let her know what we changed and didn't change. Send Canan the file - if too big give her the URL.**

From Canan May 22:

Only very few ideas that I can recommend of (not that they make any difference); 

1- The phrase that starts with "Copy each...." seems redundant on pages 11, 14, 20 and 25.

2- Instead of writing "page" you used "p." on worksheets 2 and 3. So if you would like to change them they are on pages 4, 7, 10, 11, 14, 16, 18, 20, 21, 24 and 25.

3- p.5; You can correct "2nd"on Demi- 2nd.

4 - p.16; The explanation seems redundant.

5 - p.21; Do you think adding left-diagonal stroke to the arm would be helpful for reading?

**Comment by rryman** [comment]
**DONE**

Rhonda suggested the following reply. Robyn to look at the file and give Rhonda input.

Thanks for your helpful suggestions, Canan.

1. For each chapter, the opening paragraph provides a reminder about good writing practices, which readers can easily skip if desired. We have therefore retained these. OR We have deleted the opening paragraph after Chapter 1 as per your suggestion.
2. Thanks for spotting the inconsistency. Corrected.
3. Thanks for spotting the formatting anomaly. Corrected.
4. We have included these reminders to anticipate and prevent common writing problems. OR We have deleted the this paragraph as per your suggestion.
5. The worksheets are based on BMN in the iBook which is in turn based on the RAD Foundations and Cecchetti Elementary Syllabus. In keeping with these sources, we do not use  left diagonal stroke. For static positions, the context (i.e. hand higher than leg) clarifies any ambiguity (and in sequences movement lines provide further clarity).

For consistency with the later worksheets, we have also updated the footer text: 

Writing Worksheets Based on _Benesh for Ballet: Book 1_

**Comment by rryman** [comment]
**DONE**

Rhonda, before I change the footer you need to decide on what you prefer. All three are different!
Book 1 - WRITING WORKSHEETS: BENESH FOR BALLET BOOK 1
Book 2 - WORKSHEETS: _BENESH FOR BALLET BOOK 2_ (Draft, January 2018)
Book 3 - WRITING SHEETS: BENESH FOR BALLET BOOK 3 (Draft, April 2018)

Rhonda's reply to update footer: 
Writing Worksheets Based on _Benesh for Ballet: Book 2_ 
Copyright © June 2018 Rhonda Ryman-Kane & Robyn Hughes Ryman

Robyn to update footer in pdf of Book 1; Rhonda to update footer in .doc for Books-2-4

**Comment by rryman** [comment]
**DONE**

**Acknowledgement used:
The authors wish to gratefully acknowledge the proofreading assistance of Canan Kayacik, Istanbul University State Conservatory, Department of Performing Arts, Ballet Department, Artistic Faculty.**

On page 2 of BB3 Worksheets you added:
Acknowledgements
The authors wish to gratefully acknowledge the assistance of Canan Kayacik in proofreading these Writing Sheets.

I think I should copy this to BB1 and BB2 Worksheets as well. Do you agree?

Rhonda's reply: agreed; Robyn; to update pdf of Book 1: Rhonda to update .doc of Books 2-4

**Comment by rryman** [comment]
**DONE**

Rhonda, please look at the attached page and let me know if you think this formatting works okay with the altered first paragraph. I took out the repetition and kept in what I thought was new to this chapter. I spaced out the notation below. I haven't fixed the greyed out notation as I want us to agree on the format of the page before proceeding. If you don't like the look of this page then we should just tell Canan that if we take out the redundant paragraph then it messes with the formatting too much. I don't want to have to start moving notation from one page to the other as it is a nightmare in Adobe Illustrator to do so!
[Page11_BeneshWorksheetsBook1.pdf](https://github.com/rryman/BB1-Worksheets/files/2069772/Page11_BeneshWorksheetsBook1.pdf)

Rhonda's reply: agreed to delete redundant paras but not change formatting/pagination.

On p. 11, Robyn has taken out the first 2 paragraphs and added a lead-in to para 3 (now para 1);
and has added a semi-colon after "left foot behind" **(moved this to page 12)**; same re pp. 14, 20 and 25.

**Comment by rryman** [comment]
**DONE**

Rhonda, I think Canan means make the "nd" in 2nd superscript like you have for 3rd and 4th on the same page as I can't see a space between the hyphen and the 2 in the worksheets.

Rhonda's reply: agreed; Robyn to figure out how to do this in AI.

**Comment by rryman** [comment]
**DONE**

Page 16: I think it would be helpful just to keep in the information that wasn't stated on page 14 -
Note that the wrist direction sign is attached to the basic sign for the hand. (and take out the info that is the same on page 14). Do you agree?

Rhonda's reply: Robyn to delete "that the head of a direction sign is centred below the frame; that the base of ahead/body sign is anchored to the shoulder line; and "
The para now reads: "Note that the wrist direction sign is attached to the basic sign for the hand."

**Robyn ended up deleting all the instructions on this page, because they have all been stated before and nothing is new here.**

**Comment by rryman** [comment]
**DONE**

**Robyn - before emailing Canan ask if Rhonda sent this to Canan already.**

Rhonda, I agree with your comment re Canan's #5, but I suggest adding the bits I have put in bold below. Do you agree? Reword it if it doesn't read well.
The worksheets are based on BMN in the iBook which is in turn based on the RAD Foundations and Cecchetti Elementary Syllabus. In keeping with these sources, we do not use the left diagonal stroke **for the hand that is below the waist line in arabesques, bras bas, demi-2nd, etc.** For static positions, the context (i.e. in arabesques the hand higher **and further from the centre line** than leg) clarifies any ambiguity (and in sequences movement lines provide further clarity). **The only time a left diagonal stroke would be used in an arabesque position is when the leg is above the waist line, i.e., a high arabesque. In which case the foot sign would be qualified.**

Rhonda's reply: agreed. I will communicate this to Canan.

**Comment by rsryman** [comment]
**DONE**

Re Canan's #2- Instead of writing "page" you used "p." on worksheets 2 and 3. So if you would like to change them they are on pages 4, 7, 10, 11, 14, 16, 18, 20, 21, 24 and 25.

Robyn to update "page" -> "p." and "pages" -> "pp."

**Comment by rsryman** [comment]
**DONE**

Robyn, please update the Acknowledgements (wordsmithing needed?), per Cana's email of May 16:

The authors wish to gratefully acknowledge the proofreading assistance of Canan Kayacik, Istanbul University State Conservatory, Department of Performing Arts, Ballet Department, Artist Faculty.

**Comment by rsryman** [comment]
**DONE**

Robyn, should we consider making the page references consistent with _Book 2_ worksheets, etc.:

(_Book 1_ p. ?) OR, where relevant (_Book 1_ SUMMARY p. ?)

**Comment by rsryman** [comment]
**DONE**

1. Use consistent format for the section title: 
**Positions of the Feet** (_Book 1_ Summary p. #/pp. #). 
2. Place each label place above the corresponding BMN clip, followed by a colon only if there is more info, e.g. 1st: flat/demi-pointes/pointes. See BB3 Worksheets p. 4 as a model.
3. Try to keep font size consistent
4. Add solid start/end stave bar line (instead of dashed bar line) as in BB3 from p. 6 to end

**Comment by rryman** [comment]
**DONE**

Rhonda, when you have time, please look at the attached pdf. It is BB1 Worksheets page 11.
I won't update pages 12 and 13 until we have made a decision on the format of this page.

I tried to make the format similar to BB3 Worksheets page 4.
As you did, I used 12 pt font for 1st and 2nd; and 10 pt for the flat, demi, etc.

Up to this page in BB1 Worksheets there hasn't been a colon after the 1st, etc. so I took it out here.

Note: I moved "Note: LB = left foot behind, RB = right foot behind:" to the top of page 12 as it seems more relevant.

[BB1WorksheetsP11.pdf](https://github.com/rryman/BB1-Worksheets/files/2320987/BB1WorksheetsP11.pdf)

Rhonda agrees, Aug 26, 2018.

**Comment by rryman** [comment]
**DONE**

I decided to take the time to move all the terms above the stave from pages 3 - 10.
Now it is consistent with the rest of the pages in BB1 Worksheets. Also consistent with the way it is in the BB1 ebook summary page.

**Comment by rryman** [comment]
**DONE**

Rhonda, when you have time, please look at the attached pdf. It is BB1 Worksheets page 14.

I added LF/RF/LF ... below the bottom of the notation. Do you think it is helpful to have it in, or unnecessary? I won't add it to the rest of the pages until I hear whether it should stay or go.

[BB1WorksheetsP14.pdf](https://github.com/rryman/BB1-Worksheets/files/2321059/BB1WorksheetsP14.pdf)

Rhonda and Robyn agree that the label is not needed. Robyn to remove label on p. 14 (top note & bottom line).
Also, Robyn to update: "…and that the base of a head sign is anchored to centre of the frame at the shoulder line."

**Comment by rryman** [comment]
**DONE**

Rhonda, when you have time, please look at the attached pdf. It is BB1 Worksheets page 15.

I increased the turned head by one pixel for Écarté derrière so it looks like a maximum turn.
Is this correct?

[BB1WorksheetsP15.pdf](https://github.com/rryman/BB1-Worksheets/files/2321583/BB1WorksheetsP15.pdf)

Rhonda agrees. Robyn to update intermediate wrist direction signs and head signs to match BB1.

**Comment by rryman** [comment]
**DONE**

Page 18 - Poses of the Body, Russian

FYI - Efface derriere should be a slight bend forward, not back.
I am fixing the notation in Adobe Illustrator.

Please type a **DONE** at the top of this comment when you have read this.

**Comment by rryman** [comment]
**DONE**

Updated Page 11. 
Colon added after 1st and 2nd.
Flat, demi-pointes, and pointes left aligned to bar line.

Personally I don't like this. I prefer the text centred, but if you think it looks better then I will update the other pages.

[UpdatedBB1WorksheetsP11.pdf](https://github.com/rryman/BB1-Worksheets/files/2325275/UpdatedBB1WorksheetsP11.pdf)

**Comment by rryman** [comment]
**DONE**

Sorry! I forgot to take out the colon after the first title!
I'll do that and upload it again.

**Comment by rryman** [comment]
**DONE**

Most recent Page 11 pdf - August 27th 3:12pm.

[NewlyUpdatedBB1WorksheetsP11.pdf](https://github.com/rryman/BB1-Worksheets/files/2325283/NewlyUpdatedBB1WorksheetsP11.pdf)

**Comment by rryman** [comment]
**DONE**

Decision for BB1 Worksheets:

1. No colon after the main heading (as in BB2 and BB3).
2. No colon after the name of the step, even if it has flat, demi, etc., below the stave (different than BB2 and BB3 because of dotted centre line).
3. Flat, demi-pointes, pointes will be centred in the frames (different than BB2 and BB3 because there is only one frame - the captions will be left aligned to bar line in BB2 and BB3).

**Comment by rryman** [comment]
**DONE**

Final version of Page 11 pdf - August 27th 3:33pm
Re decision above.
[LatestBB1WorksheetsP11.pdf](https://github.com/rryman/BB1-Worksheets/files/2325359/LatestBB1WorksheetsP11.pdf)

**Comment by rryman** [comment]
**DONE**

BB1 Worksheets page 19
Benesh for Ballet pages 99 - 101

What do you think of this notation?
Will it confuse the students because it is different from the ebook?
I can change it back to the original if you think that would be safer.

[BB1WorksheetsP19.pdf](https://github.com/rryman/BB1-Worksheets/files/2325539/BB1WorksheetsP19.pdf)

**Comment by rsryman** [comment]
**DONE**

It is definitely different from the eBook p. 101 but closer to the DF
figures on pages 99-100. Catch 22. Perhaps it's best to keep the BMN
consistent. Would it help to eliminate the top dot/dash in the centre line?

**Comment by rryman** [comment]
**DONE**

Okay. Here it is with the hand on top of the head as on page 101 (with the top dot/dash taken out).
Is this okay?

[UpdatedBB1WorksheetsP19.pdf](https://github.com/rryman/BB1-Worksheets/files/2328570/UpdatedBB1WorksheetsP19.pdf)

**Comment by rryman** [comment]
**DONE**

Text at the top of page 20 - reword if you feel it is necessary:

When copying each frame in the space provided below, pay careful attention to the height of the signs in relation to the stave lines and their distance from the centre of the frame.

**Comment by rsryman** [comment]
**DONE**

BMN and text agreed.

**Comment by rryman** [comment]
**DONE**
Rhonda, FYI on p. 24 of BB1 Worksheets I made the arabesque leg a little higher to match the notation in the ebook p. 131. You made the Russian arabesque leg a little higher in the DF figures so we decided to place the dot as close as possible to the waist line. (Not that it really matters, just thought I'd make it as consistent as possible while I was editing.)

Please type a bold DONE at the top of this comment when you have read it.

**Comment by rryman** [comment]
**DONE**

Rhonda, I think I may have finally finished the updates to BB1 Worksheets.
I am attaching the latest pdf to this comment for you to download.
Please give it a look over and see if anything jumps out at you.
Let me know when it is okay to start working on the BB2 Worksheets.

[2018_08_28_BeneshWorksheetsBook1.pdf](https://github.com/rryman/BB1-Worksheets/files/2330052/2018_08_28_BeneshWorksheetsBook1.pdf)
