### ISSUE TITLE
ProofreadingBB1Worksheets

### ISSUE THREAD

**Issue by rsryman** [rryman/BB1-Worksheets#4]
**DONE**

Re 2018_08_28_BeneshWorksheetsBook1: the greyed BMN looks very good. Hope the students appreciate the amount of work this took! A few points:

1. Our style sheet said consistent format for the section title: **Positions of the Feet** (_Book 1_ Summary p. #/pp. #). BUT in BB1 we say "(See/see _Book 1,_ etc." 
I found uppercase on pp. 4, 7, 10; ROBYN TO DO A GLOBAL SEARCH and change (See… -> (see… 
RHONDA TO MAKE A NOTE TO CHANGE THIS IN BB2 and BB3 WORKSHEETS

2. Consistent format for instructions. I think we should change italics to plain text 12 pt (unless smaller size needed to avoid a page break/change in format). I found this on pp. 4, 5, 6, 12, 19. ROBYN TO DO A GLOBAL SEARCH IF POSSIBLE? (The only italics we use is for _Book 1_.)

3. In _Book 1_ p. 64 we say: The sign or signs sit just below the bottom stave line to show feet flat (heels on floor), through the bottom stave line for demi-pointes (heels off floor), and on top of the bottom stave line for full pointes (tips of feet on floor). 
Wording on BB1 Worksheets p. 11 is a bit unclear (non-parallel structure). We could use the wording above, OR (your choice): …observe that the basic sign is drawn touching below the line to show…, is superimposed on the floor line to show…, and drawn touching above the floor line to show….

4. On p. 14, the reminder about the base of the head sign relates most importantly to tilts, which don't appear until the next page. Perhaps split the note? Your call.
Leave first clause on p. 14: "When copying…below the frame." Move second clause to the top of p. 15: "When copying each frame in the space provided below, note that the base of a head sign is anchored to the centre of the frame at the shoulder line." OR just: "Note that the base of a head sign is anchored to the centre of the frame at the shoulder line."

5. p. 23: in the top stave frame 4, the left knee sign is cut off (it is fine in the 2nd stave).

6. p. 25: Delete comma on line 2? Also, Robyn, is it possible to use a non-serif font for the "x" at the end of para 1 (so it looks more like the BMN sign)?

For Rhonda to update BMN files:
1. Effacé derrière, Russian: head slight forward bend
2. Écarté, Russian: max turn (visibly longer line then medium turn)
3. Arabesque, Russian: dot touches below waist line

**Comment by rryman** [comment]
**DONE**

**DONE except pp. 11, 19**
Updates completed:
√p. 4 - undid italics, took out "see"
√p. 5 - took out "Note:", undid italics, 12pt font
√p. 6 - undid italics, 12pt font
√p. 7 - took out "see"
√p. 10 - took out "see"
p. 11 - reworded instructions, took out "see" (Rhonda to check wording carefully)
**DELETE "/pointes":**
"…and is drawn touching above the floor line to show pointe (tip of foot on floor)."
√p. 12 - took out "Note:", undid italics, 12pt font
√p. 14 - split note (rest on p. 16), took out "see"
√p. 16 - Added note (from p. 14), took out "see" (Rhonda to check wording carefully. I decided it was redundant to restate ... "When copying ... below,". I hope you agree. It seems more consistent with other notes we made that are not under a chapter heading. **FINE.**
√p. 18 - took out "see"
p. 19 - undid italics, 12pt font (I underlined "lighter and finer" in keeping with p. 14, etc.) Is that okay?
**FINE but can you lower the line by 1 pixel to correspond to its clearer placement on pp. 14 & 25?**
√p. 20 - took out "see"
√p. 21 - took out "see"
√p. 22 - undid italics, 12pt font 
√p. 23 - fixed cut of left knee sign
√p. 24 - took out "see"
√p. 25 - took out comma, I used the BMN sign for the "x" , took out "see", underlined "tilts to right", and "lighter and finer" in keeping with p. 19 - I also changed "finer and thinner" to "lighter and finer" to be more consistent.) **GOOD.**
√p. 26 - took out "see"
√p. 27 - took out "see"

**Comment by rryman** [comment]
Latest BB1 Worksheets - 6:00pm August 29

[2018_08_29_BeneshWorksheetsBook1.pdf](https://github.com/rryman/BB1-Worksheets/files/2333926/2018_08_29_BeneshWorksheetsBook1.pdf)

**Comment by rryman** [comment]
Latest pdf of BB1 Worksheets - see corrections in comment above.
Wednesday August 29 - 6:16 pm

[2018_08_29_BeneshWorksheetsBook1.pdf](https://github.com/rryman/BB1-Worksheets/files/2333970/2018_08_29_BeneshWorksheetsBook1.pdf)

**Comment by rryman** [comment]
Final version
[2018_08_30_BeneshWorksheetsBook1.pdf](https://github.com/rryman/BB1-Worksheets/files/2337238/2018_08_30_BeneshWorksheetsBook1.pdf)
